
environment: dev

data:
  #task_name: csv_data_ingestor
  name: titanic
  type: csv
  path: data/raw/csv/titanic.csv
  include: all
  target_column: survived

data_validation:

  #missing value validation
  missing_value_validation:
    #task_name: missing_value_validator
    missing_percentage: 99
  
  #data type validation
  data_type_validation:
    #task_name: data_type_validator
    columns:
      col1:
        name: PassengerId
        dtype: int
      col2:
        name: Survived
        dtype: int
      col3:
        name: Pclass
        dtype: int
      col4:
        name: Name
        dtype: int
      col5:
        name: Sex
        dtype: str
      col6:
        name: Age
        dtype: float
      col7:
        name: SibSp
        dtype: int
      col8:
        name: Parch
        dtype: int
      col9:
        name: Ticket
        dtype: str
      col10:
        name: Fare
        dtype: float
      col11:
        name: Cabin
        dtype: str
      col12:
        name: Embarked
        dtype: str


  # next will be schema validation(cols exists or not ,cols have correct name or not)